// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vin_de_la_france_2.Data;

#nullable disable

namespace Vin_de_la_france_2.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vin_de_la_france_2.Models.ArticlesClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FamillesClassId")
                        .HasColumnType("int");

                    b.Property<int>("FournisseursClassId")
                        .HasColumnType("int");

                    b.Property<int>("MinimumThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityStock")
                        .HasColumnType("int");

                    b.Property<Guid>("Reference")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamillesClassId");

                    b.HasIndex("FournisseursClassId");

                    b.ToTable("ArticlesClass");
                });

            modelBuilder.Entity("Vin_de_la_france_2.Models.FamillesClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FamillesClasses");
                });

            modelBuilder.Entity("Vin_de_la_france_2.Models.FournisseursClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FournisseursClasses");
                });

            modelBuilder.Entity("Vin_de_la_france_2.Models.ArticlesClass", b =>
                {
                    b.HasOne("Vin_de_la_france_2.Models.FamillesClass", "FamillesClass")
                        .WithMany("ArticlesClasses")
                        .HasForeignKey("FamillesClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vin_de_la_france_2.Models.FournisseursClass", "FournisseursClass")
                        .WithMany("ArticlesClasses")
                        .HasForeignKey("FournisseursClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamillesClass");

                    b.Navigation("FournisseursClass");
                });

            modelBuilder.Entity("Vin_de_la_france_2.Models.FamillesClass", b =>
                {
                    b.Navigation("ArticlesClasses");
                });

            modelBuilder.Entity("Vin_de_la_france_2.Models.FournisseursClass", b =>
                {
                    b.Navigation("ArticlesClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
