// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VinWpf.DataSet;

#nullable disable

namespace VinWpf.Migrations
{
    [DbContext(typeof(PhishingContext))]
    [Migration("20240923084454_db")]
    partial class db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VinWpf.DataSet.ArticleClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FamilleClassId")
                        .HasColumnType("integer");

                    b.Property<int>("FournisseursClassId")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityStock")
                        .HasColumnType("integer");

                    b.Property<Guid>("Reference")
                        .HasColumnType("uuid");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamilleClassId");

                    b.HasIndex("FournisseursClassId");

                    b.ToTable("ArticleClass");
                });

            modelBuilder.Entity("VinWpf.DataSet.ClientsClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClientsClass");
                });

            modelBuilder.Entity("VinWpf.DataSet.CommandeClientsClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleClassId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientsClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PrixCommande")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleClassId");

                    b.HasIndex("ClientsClassId");

                    b.ToTable("CommandeClientsClass");
                });

            modelBuilder.Entity("VinWpf.DataSet.CommandeFournisseurClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleClassId");

                    b.ToTable("CommandeFournisseurClass");
                });

            modelBuilder.Entity("VinWpf.DataSet.FamilleClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FamilleClass");
                });

            modelBuilder.Entity("VinWpf.DataSet.FournisseursClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FournisseursClass");
                });

            modelBuilder.Entity("VinWpf.DataSet.ArticleClass", b =>
                {
                    b.HasOne("VinWpf.DataSet.FamilleClass", "FamilleClass")
                        .WithMany()
                        .HasForeignKey("FamilleClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VinWpf.DataSet.FournisseursClass", "FournisseursClass")
                        .WithMany()
                        .HasForeignKey("FournisseursClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilleClass");

                    b.Navigation("FournisseursClass");
                });

            modelBuilder.Entity("VinWpf.DataSet.CommandeClientsClass", b =>
                {
                    b.HasOne("VinWpf.DataSet.ArticleClass", "ArticleClass")
                        .WithMany()
                        .HasForeignKey("ArticleClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VinWpf.DataSet.ClientsClass", "ClientsClass")
                        .WithMany()
                        .HasForeignKey("ClientsClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleClass");

                    b.Navigation("ClientsClass");
                });

            modelBuilder.Entity("VinWpf.DataSet.CommandeFournisseurClass", b =>
                {
                    b.HasOne("VinWpf.DataSet.ArticleClass", "ArticleClass")
                        .WithMany()
                        .HasForeignKey("ArticleClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleClass");
                });
#pragma warning restore 612, 618
        }
    }
}
